name = "SimLynx"
uuid = "8a6c08f8-8214-4bd1-af62-0b12647b7dde"
authors = ["Dr. Doug Williams", "Anthony Dupont", "Trystan Kaes"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
