name = "SimLynx"
uuid = "8a6c08f8-8214-4bd1-af62-0b12647b7dde"
authors = ["Dr. Doug Williams", "Anthony Dupont", "Trystan Kaes"]
version = "0.2.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
